<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SHANMUK-TEJ" ignored="0" name="Default test" tests="1" failures="1" timestamp="12 May 2020 13:29:01 GMT" time="53.596" errors="0">
  <testcase name="feature" time="41.365" classname="com.myntra.testrunner.UpdateEmail">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: Portal displays &amp;quot;Something Went Wrong!&amp;quot; alert">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Portal displays "Something Went Wrong!" alert
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at com.myntra.testrunner.UpdateEmail.feature(UpdateEmail.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Portal displays "Something Went Wrong!" alert
at org.testng.Assert.fail(Assert.java:96)
at com.myntra.stepDefinitions.Steps.portal_should_ask_to_check_verification_Email(Steps.java:234)
at âœ½.Then portal should ask to check verification Email(src/main/java/com/myntra/features/updateEmail.feature:23)
]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Default test -->
