<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SHANMUK-TEJ" ignored="0" name="Validating Items Count" tests="1" failures="1" timestamp="12 May 2020 13:39:43 GMT" time="123.768" errors="0">
  <testcase name="feature" time="68.678" classname="com.myntra.testrunner.ItemsCount">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [263] but found [264]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [263] but found [264]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at com.myntra.testrunner.ItemsCount.feature(ItemsCount.java:47)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: expected [263] but found [264]
at com.myntra.stepDefinitions.Steps.count_all_items_of_that_product_and_validate(Steps.java:386)
at âœ½.Then Count all items of that product and validate(src/main/java/com/myntra/features/itemsCount.feature:15)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Validating Items Count -->
